---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check terraform binary exists
      ansible.builtin.stat:
        path: /usr/local/bin/terraform
      register: terraform_bin

    - name: Assert terraform is present
      ansible.builtin.assert:
        that: terraform_bin.stat.exists

    - name: Run terraform version
      ansible.builtin.command: terraform version
      changed_when: false
