---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check docker binary is available
      command: docker --version
      changed_when: false

    - name: Check docker compose plugin is available
      command: docker compose version
      changed_when: false
      ignore_errors: true
