---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check docker binary is available
      ansible.builtin.command: docker --version
      changed_when: false

    - name: Check docker compose plugin is available
      ansible.builtin.command: docker compose version
      changed_when: false
      failed_when: false
