---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check mongod binary is available
      ansible.builtin.command: mongod --version
      changed_when: false

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Check MongoDB service is active
      ansible.builtin.assert:
        that: ansible_facts.services['mongod.service'].state == 'running'
