---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check minikube binary exists
      stat:
        path: /usr/local/bin/minikube
      register: minikube_bin

    - name: Assert minikube is present
      assert:
        that: minikube_bin.stat.exists

    - name: Run minikube version
      command: minikube version
      changed_when: false
