---
- name: Install Python and build essentials
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - python3-dev
      - python3-setuptools
      - python3-wheel
      - python3-virtualenv
      - build-essential
    state: present
    update_cache: true
  register: python_install

- name: Install extra pip packages
  pip:
    name: "{{ python_pip_packages }}"
    state: latest
    executable: /usr/bin/pip3
    extra_args: "--break-system-packages"
  when: python_pip_packages | length > 0
