---
galaxy_info:
  author: DevOps Team
  namespace: devbox
  role_name: minikube
  description: Install Minikube local Kubernetes cluster
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - minikube
    - kubernetes
    - k8s

dependencies: []
