---
- name: Converge
  hosts: all
  become: true
  vars:
    mysql_root_password: "MOLECULE_TEST_ONLY_NOT_A_REAL_PASSWORD"
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
  roles:
    - role: mysql
