---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check MySQL is installed
      ansible.builtin.command: mysql --version
      changed_when: false

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Check MySQL service is active
      ansible.builtin.assert:
        that: ansible_facts.services['mysql.service'].state == 'running'
