---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check MySQL is installed
      ansible.builtin.command: mysql --version
      changed_when: false

    - name: Check MySQL service is active
      ansible.builtin.command: systemctl is-active mysql
      changed_when: false
