---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check git is installed
      ansible.builtin.command: git --version
      changed_when: false

    - name: Check git-extras is installed
      ansible.builtin.command: dpkg -s git-extras
      changed_when: false
