---
- name: Install Maven
  ansible.builtin.apt:
    name: maven
    state: present

- name: Verify Maven installation
  ansible.builtin.command: mvn -version
  register: maven_version
  changed_when: false
