---
galaxy_info:
  author: DevOps Team
  namespace: devbox
  role_name: openjdk
  description: Install OpenJDK
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - java
    - jdk
    - development

dependencies: []
